version: "3"
services:
  nginx:
    build:
      context: ./nginx
      args:    
        - APPLICATION_ROOT=${APPLICATION_ROOT}
    ports:
      - ${NGINX_HOST_PORT}:80
    depends_on:
      - fpm
    volumes:
      - ${APPLICATION}:/var/www/html

  fpm:
    build:
      context: ./php-fpm
    depends_on:
      - db
    volumes:
      - ${APPLICATION}:/var/www/html
 
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
  
  redis:
    image: redis
    volumes:
      - ${DATA}/redis:/data
    ports:
      - ${REDIS_HOST_PORT}:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_HOST_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
